runtime: python39

entrypoint: gunicorn -b :$PORT your_project_name.wsgi

env_variables:
  DJANGO_SETTINGS_MODULE: "your_project_name.settings"
  SECRET_KEY: "your-secret-key"
  # Add other environment variables here, such as database connection info.

handlers:
- url: /static
  static_dir: static/
- url: /.*
  script: auto
