# Generated by Django 4.2 on 2023-11-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circumcision', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anesthesia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='circumcisionprocedure',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='circumcisionprocedure',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
