# Generated by Django 4.2 on 2023-11-14 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circumcision', '0004_remove_circumcisionprocedure_emla_cream_used_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circumcisionprocedure',
            name='other_procedure_type',
        ),
        migrations.AddField(
            model_name='circumcisionprocedure',
            name='post_operative_medication',
            field=models.TextField(blank=True, null=True),
        ),
    ]
