# Generated by Django 4.2 on 2023-11-18 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circumcision', '0005_remove_circumcisionprocedure_other_procedure_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalhistory',
            old_name='has_allergies',
            new_name='anatomical_abnormalities',
        ),
        migrations.RenameField(
            model_name='medicalhistory',
            old_name='in_hiv_care_or_referred',
            new_name='antiseptics_allergy',
        ),
        migrations.RenameField(
            model_name='medicalhistory',
            old_name='knows_hiv_status',
            new_name='balanitis',
        ),
        migrations.RenameField(
            model_name='medicalhistory',
            old_name='open_wounds_or_recently_healed_scars',
            new_name='client_concented',
        ),
        migrations.RenameField(
            model_name='medicalhistory',
            old_name='date_of_td1',
            new_name='date_of_consent',
        ),
        migrations.RenameField(
            model_name='medicalhistory',
            old_name='other_sti_or_abnormality',
            new_name='drug_allergy',
        ),
        migrations.RenameField(
            model_name='medicalhistory',
            old_name='tested_hiv_last_four_weeks',
            new_name='food_allergy',
        ),
        migrations.RenameField(
            model_name='medicalhistory',
            old_name='allergies_description',
            new_name='other_allergies_specify',
        ),
        migrations.RenameField(
            model_name='medicalhistory',
            old_name='other_conditions',
            new_name='other_medical_history_specify',
        ),
        migrations.RenameField(
            model_name='medicalhistory',
            old_name='other_physical_exam_conditions',
            new_name='other_physical_exam_specify',
        ),
        migrations.RenameField(
            model_name='medicalhistory',
            old_name='date_of_td2',
            new_name='tetanus_vaccination_td1_date',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='blood_pressure',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='hiv_status',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='respiratory_rate',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='tested_hiv_this_appointment',
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='bp_diastolic',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='bp_systolic',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='difficulty_in_retracting_foreskin',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='erectile_dysfunction',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='hiv_test_result',
            field=models.CharField(blank=True, choices=[('negative', 'Negative'), ('positive', 'Positive'), ('inconclusive', 'Inconclusive'), ('known_positive', 'Known Positive'), ('unknown', 'Unknown')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='hiv_tested_during_appointment',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='hiv_tested_last_four_weeks',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='hts_offered',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='if_hiv_positive_under_care',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='local_anesthetics_allergy',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='other_sti_abnormality',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='other_treatment_specify',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='pain_on_urination',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='rr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='sexually_active',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='td_given_during_appointment',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='tetanus_vaccination_td2_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='adhesions',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='anaemia',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='bleeding_disorder',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circumcision.client'),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='diabetes',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='genital_ulcer_disease',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='genital_ulcers',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='genital_warts',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='hiv_aids',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='hypertension',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='jiggers',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='partner_hiv_status',
            field=models.CharField(blank=True, choices=[('negative', 'Negative'), ('positive', 'Positive'), ('inconclusive', 'Inconclusive'), ('known_positive', 'Known Positive'), ('unknown', 'Unknown')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='penile_warts',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='pulse',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='surgical_disorders',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='swelling_of_scrotum',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='urethra_discharge',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='urethral_discharge',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
