# Generated by Django 4.2 on 2023-11-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circumcision', '0006_rename_has_allergies_medicalhistory_anatomical_abnormalities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='payment_decription',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('credit_card', 'Credit Card'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer')], max_length=30),
        ),
        migrations.AddField(
            model_name='client',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
