# Generated by Django 4.2 on 2023-11-19 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circumcision', '0007_client_payment_decription_client_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('credit_card', 'Credit Card'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer'), ('others', 'others')], max_length=30),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='hiv_tested_during_appointment',
            field=models.BooleanField(default=False),
        ),
    ]
