# Generated by Django 4.2 on 2023-11-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circumcision', '0009_rename_client_concented_medicalhistory_eligibility_after_examination_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalhistory',
            name='client_consented',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='consent_form',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='date_of_consent',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='eligibility_after_examination',
        ),
        migrations.AddField(
            model_name='client',
            name='client_consented',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='consent_form',
            field=models.FileField(null=True, upload_to='concent_forms/'),
        ),
        migrations.AddField(
            model_name='client',
            name='date_of_consent',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='eligibility_after_examination',
            field=models.BooleanField(default=False),
        ),
    ]
